export default {
    AUTH_LOGIN_START: 'AUTH_LOGIN_START',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
    AUTH_REGISTER_START: 'AUTH_REGISTER_START',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    AUTH_REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',
    LOGOUT: 'LOGOUT'
}
