name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and Publish Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: yarn
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          CI: true
          REACT_APP_PUSHER_APP_KEY: ${{ secrets.PusherAppKey }}
          REACT_APP_PUSHER_APP_CLUSTER: ${{ secrets.PusherAppCluster }}
        with:
          coverageCommand: yarn coverage
          debug: true
